# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Add datasource_id to user_permissions and role_permissions

Revision ID: be2319f46f1f
Revises: 889c6ac22d0c
Create Date: 2025-01-05 10:57:33.760255

"""

# revision identifiers, used by Alembic.
revision = 'be2319f46f1f'
down_revision = '889c6ac22d0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('datasource_id', sa.Integer(), nullable=True))
    op.add_column('user_permissions', sa.Column('datasource_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'datasource_id')
    op.drop_column('role_permissions', 'datasource_id')
    # ### end Alembic commands ###
